# Generated by Django 3.1.7 on 2021-03-02 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='agree',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='disagree',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterModelTable(
            name='question',
            table='question',
        ),
    ]
