# Generated by Django 3.1.7 on 2021-03-03 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20210302_1606'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='agree',
        ),
        migrations.RemoveField(
            model_name='question',
            name='disagree',
        ),
        migrations.AlterModelTable(
            name='choice',
            table='choice',
        ),
    ]
